name: Continous Deployment

on:
  repository_dispatch:
    types: [deploy]

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checking out repository
        uses: actions/checkout@v4
      -
        name: Install uv
        uses: astral-sh/setup-uv@v2
      -
        name: Set up Python
        run: uv python install
      -
        name: Build release distributions
        run: uv build
      -
        name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  release-publish-pypi:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      attestations: write
    environment:
      name: pypi
      url: https://pypi.org/p/releaseer

    steps:
      -
        name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      -
        name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          attestations: true
          packages-dir: dist/
          verbose: true
          print-hash: true
      -
        name: Attestations for PYPI Artifacts
        uses: actions/attest-build-provenance@v1.4.3
        with:
          subject-path: dist/**
          subject-name: releaseer
          show-summary: true
